services:
  mysql:
    image: mariadb:10.4
    container_name: errores_db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: errores
    ports:
      - "3306:3306"
    volumes:
      - ./src/Script_BD.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: errores_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ""
    ports:
      - "8080:80"
    depends_on:
      - mysql
